package mhkif.yc.docguardian.enums;

public enum ActivityType {
    LOGIN_ATTEMPT,
    LOGIN_ATTEMPT_FAILURE,
    LOGIN_ATTEMPT_SUCCESS,
    PROFILE_UPDATE,
    PROFILE_PICTURE_UPDATE,
    ROLE_UPDATE,
    ACCOUNT_SETTINGS_UPDATE,
    PASSWORD_RESET,
    PASSWORD_UPDATE,
    TFA_UPDATE
}
